# Generated by Django 5.2.8 on 2025-11-29 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('entry', 'Giriş'), ('exit', 'Çıxış')], max_length=10)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='ScanLog',
        ),
    ]
